language: python
sudo: false

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
  matrix:
    # earliest and latest supported; last release of every year; 12.1 and 15.0
    # for txsocksx.http
    - TWISTED=Twisted==10.1.0
    - TWISTED=Twisted==17.9.0
    - TWISTED=Twisted
    
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

cache:
  directories:
    - ~/.cache/pip

install:
  - pip install -U pip
  - pip install $TWISTED 
  - pip install .
  - pip install pyOpenSSL coveralls

script: coverage run $(which trial) txsocksx
after_success: "coveralls"
